baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Siri Tech - Digipalvelut"
theme: Siri Tech

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
 # main:
  #  - identifier: blog
   #   name: Blog
    #  title: Blog posts
     # url: /blogs
     # weight: 1
    #- identifier: gallery
    #  name: Gallery
    #  title: Blog posts
    #  url: /gallery
    #  weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Siri Tech"
  description: Text about my cool site
  #staticPath: "C:\siritech\themes\hugo-profile\static\"  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    #brandName: "Siri Tech" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableservices: false
      disableContact: false
      disableblog: true      

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Siri."
    subtitle: "Your Expert in IT Services"
    content: "An experienced professional specializing in computer repair, maintenance, and bespoke web design solutions. I provide comprehensive IT services to ensure your systems run smoothly and offer cutting-edge web design to make your online presence stand out."
    image: /images/hero.jpg
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "WhatsApp Me"
      url: "https://wa.me/message/PGKR7EZAGVCZA1"
      download: false
      newPage: true


  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      

      With expertise in tackling complex IT issues and a knack for innovative web design, I'm your trusted tech partner. Equipped with a solid foundation in computer repair and maintenance, alongside a passion for crafting captivating websites, I offer a unique blend of skills.

      Based in Jyväskylä, Finland, I'm dedicated to transforming the tech landscape. Whether it's resolving stubborn computer glitches or creating immersive web experiences, I thrive on challenges that drive innovation.

      Reach out to me for all your computer and web design needs. Let's create solutions tailored to your requirements and goals.
    
    skills:
      enable: true
      title: "Here are some key areas I can assist you with:"
      items:
        - "Computer Services"
        - "Web Designing"
        - "Social Media Management"

  # Services
  services:
    enable: true
    # title: "Custom Name"
    items:
      - title: Computer Troubleshooting
        content: Swiftly diagnose and resolve computer issues for seamless performance.
      - title: Software Installation
        content: Expert installation of operating systems and software to optimize your digital experience.
      - title: Hard Disk Recovery
        content: Recover valuable data from hard disk failures with proven expertise.
      - title: Virus Removal 
        content: Protect systems from threats with comprehensive virus removal services.
      - title: Professional Web Design Services
        content: Elevate online presence with captivating web design solutions.
      - title: IT Support
        content: Reliable assistance for all your personal IT needs, ensuring hassle-free technology use.

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: nuwan.hq@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      facebook: https://facebook.com/siritech.fi
      whatsapp: https://wa.me/message/PGKR7EZAGVCZA1

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
